name: Production VCL - API routing

# This test demonstrates the new AST-based backend replacement
# Backend names must match the backend declarations in the VCL
# The parser will automatically replace the real production hostnames
# with test mock server addresses

backends:
  api_production:
    status: 200
    headers:
      Content-Type: "application/json"
      X-Service: "API"
    body: '{"message": "API response"}'

  web_production:
    status: 200
    headers:
      Content-Type: "text/html"
      X-Service: "Web"
    body: "<html>Web content</html>"

  legacy_service:
    status: 200
    headers:
      X-Service: "Legacy"
    body: "Legacy response"

scenario:
  # Test API request routes to api_production
  - at: "0s"
    request:
      url: /api/users
    expect:
      status: 200
      backend_used: "api_production"
      headers:
        X-Backend-Used: "api_production"
        X-Service: "API"

  # Test web request routes to web_production
  - at: "1s"
    request:
      url: /index.html
    expect:
      status: 200
      backend_used: "web_production"
      headers:
        X-Backend-Used: "web_production"
        X-Service: "Web"

  # Test legacy request routes to legacy_service
  - at: "2s"
    request:
      url: /legacy/old-api
    expect:
      status: 200
      backend_used: "legacy_service"
      headers:
        X-Backend-Used: "legacy_service"
        X-Service: "Legacy"
