name: API routing test

backends:
  api_backend:
    status: 200
    headers:
      X-Backend: "api"
      Content-Type: "application/json"
    body: '{"service": "api"}'

  web_backend:
    status: 200
    headers:
      X-Backend: "web"
      Content-Type: "text/html"
    body: "<html>Web content</html>"

scenario:
  # Test API request goes to api_backend
  - at: "0s"
    request:
      url: /api/users
    expectations:
      response:
        status: 200
        headers:
          X-Backend: "api"
      backend:
        used: "api_backend"

  # Test web request goes to web_backend
  - at: "1s"
    request:
      url: /index.html
    expectations:
      response:
        status: 200
        headers:
          X-Backend: "web"
      backend:
        used: "web_backend"

  # Test another API path
  - at: "2s"
    request:
      url: /api/products/123
    expectations:
      response:
        status: 200
        body_contains: "api"
      backend:
        used: "api_backend"
